import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import HeaderDefault from "@/components/molecules/HeaderDefault";

// Importa Red Hat Display como variável
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat-display",
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=add_alert"
        />
      </head>
      <body
        className={`
          ${redHatDisplay.variable}
          antialiased
        `}
      >
        <HeaderDefault></HeaderDefault>
        {children}
      </body>
    </html>
  );
}
